/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_MyJni */

#ifndef _Included_com_jni_MyJni
#define _Included_com_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_MyJni
 * Method:    callNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_MyJni_callNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
